[
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "subNode",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片1图片1",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/xxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片2",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic3",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片3",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic3"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic4",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626170574152948.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片4",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic4"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic5",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626197509499168.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片5",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic5"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zzb",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "至尊宝",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zzb"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "ll",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "大榴莲",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/ll"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zxx",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "周星星",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zjl",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "周杰伦",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zjl"
  },{
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "xxx",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626015304842872.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片1",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/xxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626066909851196.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片2",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic3",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片3",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic3"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic4",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片4",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic4"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic5",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626197509499168.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "图片5",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic5"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zzb",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "至尊宝",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zzb"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "ll",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "大榴莲",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/ll"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zxx",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "周星星",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zjl",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "周杰伦",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zjl"
  }
]