[{
    'blurImageUrl': '',
    'clickable': 0,
    'enName': 'suboer',
    'entryWord': '',
    'focusImageUrl': 'images/pic1_01.jpg',
    'isManaged': 'managed',
    'linkUrl': 'http://localhost/zhongshan_new/zs_content',
    'listType': 'list',
    'name': '苏泊尔',
    'navigator': '',
    'newAdd': 0,
    'nodePath': 'cgrk/zx/2'
  }, {
    'blurImageUrl': '',
    'clickable': 0,
    'enName': 'subNode',
    'entryWord': '',
    'focusImageUrl': 'images/pic1_02.jpg',
    'isManaged': 'managed',
    'linkUrl': 'http://localhost/zhongshan_new/zs_content',
    'listType': 'list',
    'name': '直播电视',
    'navigator': '',
    'newAdd': 0,
    'nodePath': 'cgrk/zx/2'
  }, {
    'blurImageUrl': '',
    'clickable': 0,
    'enName': 'subNode',
    'entryWord': '',
    'focusImageUrl': 'images/pic1_03.jpg',
    'isManaged': 'managed',
    'linkUrl': 'http://localhost/zhongshan_new/zs_content',
    'listType': 'list',
    'name': '电视回看',
    'navigator': '',
    'newAdd': 0,
    'nodePath': 'cgrk/zx/2'
  }, {
    'blurImageUrl': '',
    'clickable': 0,
    'enName': 'subNode',
    'entryWord': '',
    'focusImageUrl': 'images/pic1_04.jpg',
    'isManaged': 'managed',
    'linkUrl': 'http://localhost/zhongshan_new/zs_content',
    'listType': 'list',
    'name': '精彩点播',
    'navigator': '',
    'newAdd': 0,
    'nodePath': 'cgrk/zx/2'
  }]
  