[
    {
        "blurImageUrl": "",
        "enName": "17",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "U家园U家园U家园U",
        "newAdd": 4,
        "nodePath": "",
		"clickable":1,
		"linkUrl":"http://localhost/zhongshan_new/zq_level_1/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "16",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "U保险",
        "newAdd": 4,
        "nodePath": "",
		"clickable":1,
		"linkUrl":"http://localhost/zhongshan_new/jingpin_level_2/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "16",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "U保险",
        "newAdd": 4,
        "nodePath": "",
        "clickable":1,
        "linkUrl":"http://localhost/zhongshan_new/jingpin_level_2/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "16",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "U保险",
        "newAdd": 4,
        "nodePath": "",
        "clickable":1,
        "linkUrl":"http://localhost/zhongshan_new/jingpin_level_2/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "16",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "U保险",
        "newAdd": 4,
        "nodePath": "",
        "clickable":1,
        "linkUrl":"http://localhost/zhongshan_new/jingpin_level_2/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "15",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "文化中山",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":"http://localhost/zhongshan_new/rthd_level_2a/index.htm"
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育",
        "newAdd": 0,
        "nodePath": "",
        "clickable":1,
        "linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "13",
        "entryWord": "",
        "focusImageUrl": "images/ad2.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "",
        "newAdd": 4,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "12",
        "entryWord": "",
        "focusImageUrl": "images/ad0.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月12日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "11",
        "entryWord": "",
        "focusImageUrl": "images/ad1.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月11日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/ad2.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月10日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/ad0.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月9日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/ad1.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/ad2.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    }/*,{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/pic_img_17.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/pic_img_16.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/pic_img_15.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },{
        "blurImageUrl": "",
        "enName": "10",
        "entryWord": "",
        "focusImageUrl": "images/pic_img_14.png",
        "isManaged": "managed",
        "listType": "list",
        "name": "9月8日",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    }*/,
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育1",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育2",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育3",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育4",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    }/*,
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育5",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育6",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育7",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    },
    {
        "blurImageUrl": "",
        "enName": "14",
        "entryWord": "",
        "focusImageUrl": "",
        "isManaged": "managed",
        "listType": "list",
        "name": "党员教育8",
        "newAdd": 0,
        "nodePath": "",
		"clickable":1,
		"linkUrl":""
    }*/
]