[{
    "albumImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/album0.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "author": "作者",
    "content": "根据我市全面深化社会体制改革的工作部署，市食品药品监督管理局不断加强我市食品药品安全科普教育阵地实体化建设，开展了第二批中山市食品药品安全科普教育基地申报工作",
    "contentImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/content.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "date": "2016-07-20",
    "description": "描述",
    "entryImage": {
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "images/border_pop_01.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    },
    "id": 0,
    "linkUrl": "",
    "plainTxt": "",
    "subTitle": "副标题",
    "title": "科普基地参观 ",
    "videoUrl": ""
},
{
    "albumImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/album0.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "author": "作者",
    "content": "为全面贯彻落实“谁主管谁普法、谁执法谁普法”的普法责任机制，进一步提升食品药品法律法规宣传的精准性和有效性，我局在全市范围内积极推进食品药品法律大讲堂活动，取得了阶段性...",
    "contentImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/content.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "date": "2016-07-20",
    "description": "描述",
    "entryImage": {
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "images/border_pop_02.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    },
    "id": 0,
    "linkUrl": "http://www.baidu.com",
    "plainTxt": "",
    "subTitle": "副标题",
    "title": "大讲堂活动",
    "videoUrl": "http://172.25.0.72:8950/appcms/demo/demo.mp4"
},
{
    "albumImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/album0.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "author": "作者",
    "content": "为全面贯彻落实“谁主管谁普法、谁执法谁普法”的普法责任机制，进一步提升食品药品法律法规宣传的精准性和有效性，我局在全市范围内积极推进食品药品法律大讲堂活动，取得了阶段性...",
    "contentImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/content.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "date": "2016-07-20",
    "description": "描述",
    "entryImage": {
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "images/border_pop_03.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    },
    "id": 0,
    "linkUrl": "http://www.baidu.com",
    "plainTxt": "",
    "subTitle": "副标题",
    "title": "志愿服务活动",
    "videoUrl": "http://172.25.0.72:8950/appcms/demo/demo.mp4"
},
{
    "albumImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/album0.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "author": "作者",
    "content": "为全面贯彻落实“谁主管谁普法、谁执法谁普法”的普法责任机制，进一步提升食品药品法律法规宣传的精准性和有效性，我局在全市范围内积极推进食品药品法律大讲堂活动，取得了阶段性...",
    "contentImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/content.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "date": "2016-07-20",
    "description": "描述",
    "entryImage": {
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "images/border_pop_02.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    },
    "id": 0,
    "linkUrl": "http://www.baidu.com",
    "plainTxt": "",
    "subTitle": "副标题",
    "title": "大讲堂活动",
    "videoUrl": "http://172.25.0.72:8950/appcms/demo/demo.mp4"
},
{
    "albumImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/album0.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "author": "作者",
    "content": "为全面贯彻落实“谁主管谁普法、谁执法谁普法”的普法责任机制，进一步提升食品药品法律法规宣传的精准性和有效性，我局在全市范围内积极推进食品药品法律大讲堂活动，取得了阶段性...",
    "contentImages": [{
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "http://172.25.0.72:8950/appcms/demo/content.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    }],
    "date": "2016-07-20",
    "description": "描述",
    "entryImage": {
        "entryId": 0,
        "id": 0,
        "imageHeight": 0,
        "imageName": "",
        "imageUrl": "images/border_pop_03.png",
        "imageWidth": 0,
        "position": 0,
        "uniqueName": ""
    },
    "id": 0,
    "linkUrl": "http://www.baidu.com",
    "plainTxt": "",
    "subTitle": "副标题",
    "title": "志愿服务活动",
    "videoUrl": "http://172.25.0.72:8950/appcms/demo/demo.mp4"
}]