var pinyin = "a,ai,ao,an,ang,ba,bai,ban,bang,bao,bei,ben,beng,bi,bian,biao,bie,bin,bing,bo,bu,ca,cai,can,cang,cao,ce,cen,ceng,cha,chai,chan,chang,chao,che,chen,cheng,chi,chong,chou,chu,chua,chuai,chuan,chuang,chui,chun,chuo,ci,cong,cou,cu,cuan,cui,cun,cuo,da,dai,dan,dang,dao,de,den,dei,deng,di,dia,dian,diao,die,ding,diu,dong,dou,du,duan,dui,dun,duo,e,ei,en,eng,er,fa,fan,fang,fei,fen,feng,fo,fou,fu,ga,gai,gan,gang,gao,ge,gei,gen,geng,gong,gou,gu,gua,guai,guan,guang,gui,gun,guo,ha,hai,han,hang,hao,he,hei,hen,heng,hong,hou,hu,hua,huai,huan,huang,hui,hun,huo,i,ji,jia,jian,jiang,jiao,jie,jin,jing,jiong,jiu,ju,juan,jue,jun,ka,kai,kan,kang,kao,ke,ken,keng,kong,kou,ku,kua,kuai,kuan,kuang,kui,kun,kuo,la,lai,lan,lang,lao,le,lei,leng,li,lia,lian,liang,liao,lie,lin,ling,liu,long,lou,lu,lv,luan,lue,lve,lun,luo,m,ma,mai,man,mang,mao,me,mei,men,meng,mi,mian,miao,mie,min,ming,miu,mo,mou,mu,na,nai,nan,nang,nao,ne,nei,nen,neng,ni,nian,niang,niao,nie,nin,ning,niu,nong,nou,nu,nv,nuan,nve,nuo,nun,o,ou,pa,pai,pan,pang,pao,pei,pen,peng,pi,pian,piao,pie,pin,ping,po,pou,pu,qi,qia,qian,qiang,qiao,qie,qin,qing,qiong,qiu,qu,quan,que,qun,ran,rang,rao,re,ren,reng,ri,rong,rou,ru,ruan,rui,run,ruo,sa,sai,san,sang,sao,se,sen,seng,sha,shai,shan,shang,shao,she,shei,shen,sheng,shi,shou,shu,shua,shuai,shuan,shuang,shui,shun,shuo,si,song,sou,su,suan,sui,sun,suo,ta,tai,tan,tang,tao,te,teng,ti,tian,tiao,tie,ting,tong,tou,tu,tuan,tui,tun,tuo,u,v,wa,wai,wan,wang,wei,wen,weng,wo,wu,xi,xia,xian,xiang,xiao,xie,xin,xing,xiong,xiu,xu,xuan,xue,xun,ya,yan,yang,yao,ye,yi,yin,ying,yo,yong,you,yu,yuan,yue,yun,za,zai,zan,zang,zao,ze,zei,zen,zeng,zha,zhai,zhan,zhang,zhao,zhe,zhei,zhen,zheng,zhi,zhong,zhou,zhu,zhua,zhuai,zhuan,zhuang,zhui,zhun,zhuo,zi,zong,zou,zu,zuan,zui,zun,zuo";

/**
 * [idArr 键盘div对象]
 * ids：键盘格子对应的id，value，键盘格子对应显示的数据，index：该ids下哪一个格子显示数据，即ids对应显示数据格子的下标
 * type：【0：数字，1：字母，2：A/a 即字母大小写转换，3：清空，4：中英文切换】
 * @type {Array}
 */
var idArr = [
	{ids:["num1","num1_1"],value:1,index:0,type:0},
	{ids:["num2"],value:2,index:1,type:0},
	{ids:["num3"],value:3,index:2,type:0},
	{ids:["e0"],value:"Q",index:0,type:1},
	{ids:["e1"],value:"W",index:1,type:1},
	{ids:["e2"],value:"E",index:2,type:1},
	{ids:["e3"],value:"R",index:3,type:1},
	{ids:["e4"],value:"T",index:4,type:1},
	{ids:["e5"],value:"Y",index:5,type:1},
	{ids:["e6"],value:"U",index:6,type:1},
	{ids:["e7"],value:"I",index:7,type:1},
	{ids:["e8"],value:"O",index:8,type:1},
	{ids:["e9","e9_9"],value:"P",index:9,type:1},
	
	{ids:["num4","num4_4"],value:4,index:3,type:0},
	{ids:["num5"],value:5,index:4,type:0},
	{ids:["num6"],value:6,index:5,type:0},
	{ids:["e10"],value:"A/a",index:0,type:2},
	{ids:["e11"],value:"A",index:10,type:1},
	{ids:["e12"],value:"S",index:11,type:1},
	{ids:["e13"],value:"D",index:12,type:1},
	{ids:["e14"],value:"F",index:13,type:1},
	{ids:["e15"],value:"G",index:14,type:1},
	{ids:["e16"],value:"H",index:15,type:1},
	{ids:["e17"],value:"J",index:16,type:1},
	{ids:["e18"],value:"K",index:17,type:1},
	{ids:["e19", "e19_19"],value:"L",index:18,type:1},
	
	{ids:["num7","num7_7","num7_7_7","num7_7_7_7"],value:7,index:6,type:0},
	{ids:["num8","num8_8"],value:8,index:7,type:0},
	{ids:["num9","num9_9"],value:9,index:8,type:0},
	{ids:["num0","num0_0"],value:0,index:9,type:0},
	{ids:["e20","e20_20"],value:"中/英",index:0,type:4},
	{ids:["e21","e21_21"],value:"Z",index:19,type:1},
	{ids:["e22","e22_22"],value:"X",index:20,type:1},
	{ids:["e23","e23_23"],value:"C",index:21,type:1},
	{ids:["e24","e24_24"],value:"V",index:22,type:1},
	{ids:["e25","e25_25"],value:"B",index:23,type:1},
	{ids:["e26","e26_26"],value:"N",index:24,type:1},
	{ids:["e27","e27_27"],value:"M",index:25,type:1},
	{ids:["t0","t0_0", "t0_0_0","t0_0_0_0"],value:"清空",index:0,type:3}
];


var idArrCopy = [
	{ids:["num1","num1_1"],value:1,index:0,type:0},
	{ids:["num2"],value:2,index:1,type:0},
	{ids:["num3"],value:3,index:2,type:0},
	{ids:["e0"],value:"A",index:0,type:1},
	{ids:["e1"],value:"B",index:1,type:1},
	{ids:["e2"],value:"C",index:2,type:1},
	{ids:["e3"],value:"D",index:3,type:1},
	{ids:["e4"],value:"E",index:4,type:1},
	{ids:["e5"],value:"F",index:5,type:1},
	{ids:["e6"],value:"G",index:6,type:1},
	{ids:["e7"],value:"H",index:7,type:1},
	{ids:["e8"],value:"I",index:8,type:1},
	{ids:["e9","e9_9"],value:"J",index:9,type:1},
	
	{ids:["num4","num4_4"],value:4,index:3,type:0},
	{ids:["num5"],value:5,index:4,type:0},
	{ids:["num6"],value:6,index:5,type:0},
	{ids:["e10"],value:"A/a",index:0,type:2},
	{ids:["e11"],value:"K",index:10,type:1},
	{ids:["e12"],value:"L",index:11,type:1},
	{ids:["e13"],value:"M",index:12,type:1},
	{ids:["e14"],value:"N",index:13,type:1},
	{ids:["e15"],value:"O",index:14,type:1},
	{ids:["e16"],value:"P",index:15,type:1},
	{ids:["e17"],value:"Q",index:16,type:1},
	{ids:["e18"],value:"R",index:17,type:1},
	{ids:["e19", "e19_19"],value:"S",index:18,type:1},
	
	{ids:["num7","num7_7","num7_7_7","num7_7_7_7"],value:7,index:6,type:0},
	{ids:["num8","num8_8"],value:8,index:7,type:0},
	{ids:["num9","num9_9"],value:9,index:8,type:0},
	{ids:["num0","num0_0"],value:0,index:9,type:0},
	{ids:["e20","e20_20"],value:"中/英",index:0,type:4},
	{ids:["e21","e21_21"],value:"T",index:19,type:1},
	{ids:["e22","e22_22"],value:"U",index:20,type:1},
	{ids:["e23","e23_23"],value:"V",index:21,type:1},
	{ids:["e24","e24_24"],value:"W",index:22,type:1},
	{ids:["e25","e25_25"],value:"X",index:23,type:1},
	{ids:["e26","e26_26"],value:"Y",index:24,type:1},
	{ids:["e27","e27_27"],value:"Z",index:25,type:1},
	{ids:["t0","t0_0", "t0_0_0","t0_0_0_0"],value:"清空",index:0,type:3}
];

// 数组显示id
var numIdArr = [
	{ids:["num1","num1_1"],value:1},
	{ids:["num2"],value:2},
	{ids:["num3"],value:3},
	{ids:["num4","num4_4"],value:4},
	{ids:["num5"],value:5},
	{ids:["num6"],value:6},
	{ids:["num7","num7_7","num7_7_7","num7_7_7_7"],value:7},
	{ids:["num8","num8_8"],value:8},
	{ids:["num9","num9_9"],value:9},
	{ids:["num0","num0_0"],value:0}
];

/* 按键盘排列字母对应的id */
var letterIdArr = [
	{ids:["e0"],value:"Q"},
	{ids:["e1"],value:"W"},
	{ids:["e2"],value:"E"},
	{ids:["e3"],value:"R"},
	{ids:["e4"],value:"T"},
	{ids:["e5"],value:"Y"},
	{ids:["e6"],value:"U"},
	{ids:["e7"],value:"I"},
	{ids:["e8"],value:"O"},
	{ids:["e9"],value:"P"},
	{ids:["e11"],value:"A"},
	{ids:["e12"],value:"S"},
	{ids:["e13"],value:"D"},
	{ids:["e14"],value:"F"},
	{ids:["e15"],value:"G"},
	{ids:["e16"],value:"H"},
	{ids:["e17"],value:"J"},
	{ids:["e18"],value:"K"},
	{ids:["e19"],value:"L"},
	
	{ids:["e21","e21_21"],value:"Z"},
	{ids:["e22","e22_22"],value:"X"},
	{ids:["e23","e23_23"],value:"C"},
	{ids:["e24","e24_24"],value:"V"},
	{ids:["e25","e25_25"],value:"B"},
	{ids:["e26","e26_26"],value:"N"},
	{ids:["e27","e27_27"],value:"M"}
];

/* 按顺序排列的字母对应的id */
var letterIdArrCopy = [
	{ids:["e0"],value:"A"},
	{ids:["e1"],value:"B"},
	{ids:["e2"],value:"C"},
	{ids:["e3"],value:"D"},
	{ids:["e4"],value:"E"},
	{ids:["e5"],value:"F"},
	{ids:["e6"],value:"G"},
	{ids:["e7"],value:"H"},
	{ids:["e8"],value:"I"},
	{ids:["e9"],value:"J"},
	{ids:["e11"],value:"K"},
	{ids:["e12"],value:"L"},
	{ids:["e13"],value:"M"},
	{ids:["e14"],value:"N"},
	{ids:["e15"],value:"O"},
	{ids:["e16"],value:"P"},
	{ids:["e17"],value:"Q"},
	{ids:["e18"],value:"R"},
	{ids:["e19"],value:"S"},
	
	{ids:["e21","e21_21"],value:"T"},
	{ids:["e22","e22_22"],value:"U"},
	{ids:["e23","e23_23"],value:"V"},
	{ids:["e24","e24_24"],value:"W"},
	{ids:["e25","e25_25"],value:"X"},
	{ids:["e26","e26_26"],value:"Y"},
	{ids:["e27","e27_27"],value:"Z"}
];

// 按键盘排列的小写字母
var LletterArr = [
	{txt:"q",img:""},
	{txt:"w",img:""},
	{txt:"e",img:""},
	{txt:"r",img:""},
	{txt:"t",img:""},
	{txt:"y",img:""},
	{txt:"u",img:""},
	{txt:"i",img:""},
	{txt:"o",img:""},
	{txt:"p",img:""},
	{txt:"a",img:""},
	{txt:"s",img:""},
	{txt:"d",img:""},
	{txt:"f",img:""},
	{txt:"g",img:""},
	{txt:"h",img:""},
	{txt:"j",img:""},
	{txt:"k",img:""},
	{txt:"l",img:""},
	{txt:"z",img:""},
	{txt:"x",img:""},
	{txt:"c",img:""},
	{txt:"v",img:""},
	{txt:"b",img:""},
	{txt:"n",img:""},
	{txt:"m",img:""}
];   
// 按顺序排列的小写字母
var LletterArrCopy = [
	{txt:"a",img:""},
	{txt:"b",img:""},
	{txt:"c",img:""},
	{txt:"d",img:""},
	{txt:"e",img:""},
	{txt:"f",img:""},
	{txt:"g",img:""},
	{txt:"h",img:""},
	{txt:"i",img:""},
	{txt:"j",img:""},
	{txt:"k",img:""},
	{txt:"l",img:""},
	{txt:"m",img:""},
	{txt:"n",img:""},
	{txt:"o",img:""},
	{txt:"p",img:""},
	{txt:"q",img:""},
	{txt:"r",img:""},
	{txt:"s",img:""},
	{txt:"t",img:""},
	{txt:"u",img:""},
	{txt:"v",img:""},
	{txt:"w",img:""},
	{txt:"x",img:""},
	{txt:"y",img:""},
	{txt:"z",img:""}
];  
// 按键盘排列的大写字母
var UletterArr = [
	{txt:"Q",img:""},
	{txt:"W",img:""},
	{txt:"E",img:""},
	{txt:"R",img:""},
	{txt:"T",img:""},
	{txt:"Y",img:""},
	{txt:"U",img:""},
	{txt:"I",img:""},
	{txt:"O",img:""},
	{txt:"P",img:""},
	{txt:"A",img:""},
	{txt:"S",img:""},
	{txt:"D",img:""},
	{txt:"F",img:""},
	{txt:"G",img:""},
	{txt:"H",img:""},
	{txt:"J",img:""},
	{txt:"K",img:""},
	{txt:"L",img:""},
	{txt:"Z",img:""},
	{txt:"X",img:""},
	{txt:"C",img:""},
	{txt:"V",img:""},
	{txt:"B",img:""},
	{txt:"N",img:""},
	{txt:"M",img:""}
];	

// 按顺序排列的大写字母
var UletterArrCopy = [
	{txt:"A",img:""},
	{txt:"B",img:""},
	{txt:"C",img:""},
	{txt:"D",img:""},
	{txt:"E",img:""},
	{txt:"F",img:""},
	{txt:"G",img:""},
	{txt:"H",img:""},
	{txt:"I",img:""},
	{txt:"J",img:""},
	{txt:"K",img:""},
	{txt:"L",img:""},
	{txt:"M",img:""},
	{txt:"N",img:""},
	{txt:"O",img:""},
	{txt:"P",img:""},
	{txt:"Q",img:""},
	{txt:"R",img:""},
	{txt:"S",img:""},
	{txt:"T",img:""},
	{txt:"U",img:""},
	{txt:"V",img:""},
	{txt:"W",img:""},
	{txt:"X",img:""},
	{txt:"Y",img:""},
	{txt:"Z",img:""}
];	