[
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "xxx",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626015304842872.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬1",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/xxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626066909851196.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬2",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic3",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬3",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic3"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic4",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626170574152948.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬4",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic4"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic5",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626197509499168.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬5",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic5"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zzb",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÁ×ð±¦",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zzb"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "ll",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "´óÁñÁ«",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/ll"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zxx",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÜÐÇÐÇ",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zjl",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÜ½ÜÂ×",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zjl"
  },{
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "xxx",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626015304842872.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬1",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/xxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626066909851196.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬2",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic3",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬3",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic3"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic4",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬4",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic4"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "pic5",
    "entryWord": "",
    "focusImageUrl": "http://192.168.18.66:80/appcmsFiles_3.0/1478626197509499168.png",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "Í¼Æ¬5",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/pic5"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zzb",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÁ×ð±¦",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zzb"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "ll",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "´óÁñÁ«",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/ll"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zxx",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÜÐÇÐÇ",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zxx"
  },
  {
    "blurImageUrl": "",
    "clickable": 1,
    "enName": "zjl",
    "entryWord": "",
    "focusImageUrl": "",
    "isManaged": "managed",
    "linkUrl": "",
    "listType": "list",
    "name": "ÖÜ½ÜÂ×",
    "navigator": "",
    "newAdd": 0,
    "nodePath": "movie/zjl"
  }
]