{
	home_tagline:"民生民愿，踪",
	home_menu:[
	    {home_pic:"shdc_pic.png",home_content:"选择百姓最为关切的社会、生活、民生等类话题进行调查，也可配合政府各部门开展各类民意调查。"},
		{home_pic:"hzdc_pic.png",home_content:"将与第三方调查机构或商业公司合作，为第三方提供数据调查平台，探索在线商业调查模式，为商业公。"},
		{home_pic:"ghdc_pic.png",home_content:"主要针对歌华高清交互电视平台及歌华有线自有业务进行调查，内容将包括高清交互业务、歌华宽带。"}	
		],
	home_marquee:"跑马灯内容1跑马灯内容2跑马灯内容3跑马灯内容4跑马灯内容5跑马灯内容6跑马灯内容7跑马灯内容8跑马灯内容9"
}
