[{
  'blurImageUrl': '',
  'clickable': 1,
  'enName': '1',
  'entryWord': '撒旦撒旦撒旦撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦撒旦法撒旦法撒旦法法法撒旦撒旦撒旦法撒旦撒旦法法撒旦法撒旦法撒旦法撒旦法法撒旦撒旦撒旦法撒旦法撒旦法法撒旦撒旦法法撒旦撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法法法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法撒旦法法',
  'focusImageUrl': 'images/pic2_01.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content/index.htm',
  'listType': 'l', 'name': '9月1日', 'navigator': '', 'newAdd': 0,
  'nodePath': 'cgrk/zx/1'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_02.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_03.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_04.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_05.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_06.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_07.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}, {
  'blurImageUrl': '',
  'clickable': 0,
  'enName': '2',
  'entryWord': '',
  'focusImageUrl': 'images/pic2_08.png',
  'isManaged': 'managed',
  'linkUrl': 'http://localhost/zhongshan_new/zs_content',
  'listType': 'list', 'name': '9月2日',
  'navigator': '',
  'newAdd': 0,
  'nodePath': 'cgrk/zx/2'
}]
